services:
  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:latest
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin

        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://ep-rapid-art-a19zj9ql.ap-southeast-1.aws.neon.tech/Keycloak?sslmode=require
        KC_DB_USERNAME: voterRegistration_owner
        KC_DB_PASSWORD: bAEhOwT8BiP9

        KC_HOSTNAME: https://keycloak.lahirujayathilake.me
        KC_FEATURES: hostname
 
        KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
        KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    ports:
        - "8086:8080"
    networks:
        - keycloak
    restart: unless-stopped
    command: ["start-dev", "--import-realm"]
    volumes:
        - ./keycloak/realms/:/opt/keycloak/data/import/
        - ./keycloak/Theme2/:/opt/keycloak/providers/
        - /etc/ssl/certs/your-certificate.crt:/etc/x509/https/tls.crt
        - /etc/ssl/private/your-private.key:/etc/x509/https/tls.key

networks:
  keycloak:
    driver: bridge


